name: Terraform CI
run-name: Build run by ${{ github.actor }} on ${{ github.ref_name }}

on:
  push:
    branches:
      - 'feature/**'
      - 'bug/**'
    paths:
      - 'infra/aws/tf/**'
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  security-events: write

jobs:
  terraform-ci:
    name: CI
    uses: subhamay-bhattacharyya-gha/tf-ci-reusable-wf/.github/workflows/ci.yaml@main
    with:
      cloud-provider: aws
      tflint-ver: ${{ vars.TF_LINT_VER }}
      backend-type: remote
      tf-vars-file: environments/${{ github.event.inputs.environment }}/terraform.tfvars

